name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name fooddeliveryacr123

      - name: Build and Push Image
        run: |
          docker build -t fooddeliveryacr123.azurecr.io/restaurant-service:v1 -f Restaurantservice/Dockerfile ./Restaurantservice
          docker push fooddeliveryacr123.azurecr.io/restaurant-service:v1

      - name: Deploy Container App
        run: |
          az containerapp up \
            --name restaurant-app \
            --resource-group food-rg \
            --environment food-env \
            --image fooddeliveryacr123.azurecr.io/restaurant-service:v1 \
            --target-port 5000 \
            --ingress external \
            --location eastus
